import React from "react";

const Logo = () => {
  return (
    <svg
      id="splash-flag"
      xmlns="http://www.w3.org/2000/svg"
      className="h-16 sm:h-32 w-16 sm:w-32 opacity-0"
      fill="#FFD700"
      viewBox="0 0 64.001 64.001"
    >
      <g stroke="#FFD700">
        <path
          strokeLinecap="undefined"
          strokeLinejoin="undefined"
          strokeWidth="2"
          d="M7.831 11.668L21.757 62.955"
        ></path>
        <text
          x="14.518"
          y="35.017"
          strokeWidth="0"
          cursor="move"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 16.464 32.6)"
          xmlSpace="preserve"
        >
          1
        </text>
        <text
          x="17.631"
          y="31.495"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 19.597 29.078)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="21.236"
          y="29.119"
          strokeWidth="0"
          cursor="move"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 23.182 26.702)"
          xmlSpace="preserve"
        >
          1
        </text>
        <text
          x="25.087"
          y="27.562"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 27.053 25.145)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="29.347"
          y="26.988"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.9"
          textAnchor="start"
          transform="rotate(-14.597 31.313 24.572)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="33.689"
          y="27.152"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.8"
          textAnchor="start"
          transform="rotate(-14.597 35.636 24.735)"
          xmlSpace="preserve"
        >
          1
        </text>
        <text
          x="38.195"
          y="27.726"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.7"
          textAnchor="start"
          transform="rotate(-14.597 40.161 25.309)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="42.374"
          y="28.791"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.6"
          textAnchor="start"
          transform="rotate(-14.597 44.34 26.374)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="46.552"
          y="28.873"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.5"
          textAnchor="start"
          transform="rotate(-14.597 48.518 26.456)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="50.648"
          y="28.463"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.4"
          textAnchor="start"
          transform="rotate(-14.597 52.615 26.046)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="54.335"
          y="27.562"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.3"
          textAnchor="start"
          transform="rotate(-14.597 56.282 25.145)"
          xmlSpace="preserve"
        >
          1
        </text>
        <text
          x="13.043"
          y="29.692"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 15.01 27.275)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="11.65"
          y="24.449"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 13.617 22.032)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="10.257"
          y="19.041"
          strokeWidth="0"
          cursor="move"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 12.224 16.624)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="16.32"
          y="25.923"
          strokeWidth="0"
          cursor="move"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 18.287 23.506)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="8.701"
          y="13.634"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 10.647 11.217)"
          xmlSpace="preserve"
        >
          1
        </text>
        <text
          x="15.091"
          y="20.352"
          strokeWidth="0"
          cursor="move"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 17.038 17.935)"
          xmlSpace="preserve"
        >
          1
        </text>
        <text
          x="20.007"
          y="23.465"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 21.973 21.049)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="13.78"
          y="15.191"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 15.747 12.774)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="12.306"
          y="9.865"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 14.272 7.448)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="18.696"
          y="18.058"
          strokeWidth="0"
          cursor="move"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 20.663 15.641)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="17.385"
          y="12.733"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 19.352 10.316)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="15.911"
          y="7.571"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 17.857 5.154)"
          xmlSpace="preserve"
        >
          1
        </text>
        <text
          x="24.103"
          y="22.073"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 26.07 19.656)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="22.629"
          y="16.911"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 24.595 14.494)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="21.318"
          y="11.668"
          strokeWidth="0"
          cursor="move"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 23.284 9.25)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="19.925"
          y="6.342"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          textAnchor="start"
          transform="rotate(-14.597 21.891 3.925)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="28.2"
          y="21.581"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.9"
          textAnchor="start"
          transform="rotate(-14.597 30.166 19.164)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="26.971"
          y="16.338"
          strokeWidth="0"
          cursor="move"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.9"
          textAnchor="start"
          transform="rotate(-14.597 28.917 13.92)"
          xmlSpace="preserve"
        >
          1
        </text>
        <text
          x="25.414"
          y="10.93"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.9"
          textAnchor="start"
          transform="rotate(-14.597 27.38 8.513)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="23.94"
          y="5.687"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.9"
          textAnchor="start"
          transform="rotate(-14.597 25.906 3.27)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="32.542"
          y="21.745"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.8"
          textAnchor="start"
          transform="rotate(-14.597 34.508 19.328)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="31.231"
          y="16.42"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.8"
          textAnchor="start"
          transform="rotate(-14.597 33.198 14.003)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="29.757"
          y="11.176"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.8"
          textAnchor="start"
          transform="rotate(-14.597 31.723 8.76)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="28.282"
          y="6.097"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.8"
          textAnchor="start"
          transform="rotate(-14.597 30.228 3.68)"
          xmlSpace="preserve"
        >
          1
        </text>
        <text
          x="37.048"
          y="22.482"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.7"
          textAnchor="start"
          transform="rotate(-14.597 39.014 20.065)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="35.819"
          y="17.075"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.7"
          textAnchor="start"
          transform="rotate(-14.597 37.786 14.658)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="34.426"
          y="11.75"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.7"
          textAnchor="start"
          transform="rotate(-14.597 36.393 9.333)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="32.952"
          y="6.588"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.7"
          textAnchor="start"
          transform="rotate(-14.597 34.898 4.171)"
          xmlSpace="preserve"
        >
          1
        </text>
        <text
          x="41.309"
          y="23.302"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.6"
          textAnchor="start"
          transform="rotate(-14.597 43.255 20.885)"
          xmlSpace="preserve"
        >
          1
        </text>
        <text
          x="40.162"
          y="17.976"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.6"
          textAnchor="start"
          transform="rotate(-14.597 42.128 15.56)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="38.687"
          y="12.487"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.6"
          textAnchor="start"
          transform="rotate(-14.597 40.653 10.07)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="37.294"
          y="7.162"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.6"
          textAnchor="start"
          transform="rotate(-14.597 39.26 4.745)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="45.241"
          y="23.547"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.5"
          textAnchor="start"
          transform="rotate(-14.597 47.207 21.13)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="44.176"
          y="18.304"
          strokeWidth="0"
          cursor="move"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.5"
          textAnchor="start"
          transform="rotate(-14.597 46.142 15.887)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="43.029"
          y="13.06"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.5"
          textAnchor="start"
          transform="rotate(-14.597 44.975 10.644)"
          xmlSpace="preserve"
        >
          1
        </text>
        <text
          x="41.718"
          y="7.653"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.5"
          textAnchor="start"
          transform="rotate(-14.597 43.665 5.236)"
          xmlSpace="preserve"
        >
          1
        </text>
        <text
          x="49.338"
          y="23.138"
          strokeWidth="0"
          cursor="move"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.4"
          textAnchor="start"
          transform="rotate(-14.597 51.304 20.72)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="48.109"
          y="17.894"
          strokeWidth="0"
          cursor="move"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.4"
          textAnchor="start"
          transform="rotate(-14.597 50.075 15.477)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="46.962"
          y="12.405"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.4"
          textAnchor="start"
          transform="rotate(-14.597 48.928 9.988)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="45.815"
          y="7.162"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.4"
          textAnchor="start"
          transform="rotate(-14.597 47.78 4.745)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="53.27"
          y="22.4"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.3"
          textAnchor="start"
          transform="rotate(-14.597 55.236 19.983)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="52.123"
          y="17.075"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.3"
          textAnchor="start"
          transform="rotate(-14.597 54.09 14.658)"
          xmlSpace="preserve"
        >
          0
        </text>
        <text
          x="50.812"
          y="11.75"
          strokeWidth="0"
          cursor="move"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.3"
          textAnchor="start"
          transform="rotate(-14.597 52.759 9.333)"
          xmlSpace="preserve"
        >
          1
        </text>
        <text
          x="49.829"
          y="6.424"
          strokeWidth="0"
          fontFamily="'Arimo'"
          fontSize="7"
          fontWeight="bold"
          opacity="0.3"
          textAnchor="start"
          transform="rotate(-14.597 51.795 4.007)"
          xmlSpace="preserve"
        >
          0
        </text>
        <path
          strokeWidth="0"
          d="M7.913 12.897a.983.983 0 110-1.966.983.983 0 010 1.966z"
          opacity="undefined"
        ></path>
        <path
          strokeWidth="0"
          d="M21.677 63.61a.983.983 0 110-1.965.983.983 0 010 1.966z"
          opacity="undefined"
        ></path>
      </g>
    </svg>
  );
};

export default Logo;
